name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: bash
      run: ls > test.log
      shell: bash
    - name: output
      run: cat test.log
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_PUSH_TOKEN }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.1.0
      with:
        context: .
        push: true
        tags: khaihoangdev/nginx-ui:latest
      
      
